version: '3'
services:
  api:
    build:
      context: .
      dockerfile: PaymentGateway.API/Dockerfile
    ports:      
      - "7000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "DPwKe5R1pq6t47vHnuU2"
      ACCEPT_EULA: "Y"